### ISSUE TITLE
是不是有个崩坏三的插件来着？

### ISSUE THREAD

**Issue by becteria** [yhArcadia/Yunzai-Bot-plugins-index#28]
如题，现在无了吗？
![2(5ILC`YW4A34N@ZYP)VDQH](https://user-images.githubusercontent.com/51076246/198502812-f064667d-55fc-412c-97e5-95ed449d743e.gif)

**Comment by yhArcadia** [comment]
似乎没有这个印象

**Comment by becteria** [comment]
> 似乎没有这个印象

是py插件，另外有个xiaoyao-cvs-plugin，这个插件（是有崩坏3签到的）好像也是云崽的，但是在这个插件索引里没看到哎，地址：https://github.com/Ctrlcvs/xiaoyao-cvs-plugin
