### ISSUE TITLE
关于存在恶意代码插件的举报

### ISSUE THREAD

**Issue by tokai-rudolf** [yhArcadia/Yunzai-Bot-plugins-index#72]
yeyang52/yenai-plugin/issues/71

https://github.com/yeyang52/yenai-plugin/blob/dc575240ffc43ce7e6924eef89bf50d4dae634ef/apps/groupAdmin/groupAdmin.js#L198-L201

涉及获取管理权限的恶意代码，希望能做出关于不要更新版本的警示或者直接下架。

**Comment by SmallK111407** [comment]
有没有可能索引库也是我在管？？
